# Use postgres/example user/password credentials
version: '3.5'

services:
  dbwebcv:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:qwerty123
    ports:
      - "5432:5432"